FROM docker.all-hands.dev/all-hands-ai/openhands:0.13

ENV SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.13-nikolaik
ENV LOG_ALL_EVENTS=true

# Add any additional configurations or installations if needed